name: Auto Merge on Label

on:
  pull_request:
    types: [labeled]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Merge into QA
        if: github.event.label.name == 'merge-to-qa'  # Nombre de la etiqueta aquí
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'you@example.com'
          git rev-parse --abbrev-ref HEAD
          git status
          git fetch
          git checkout -b auto-merge/$GITHUB_HEAD_REF
          git checkout QA

          # Merge changes
          if git merge --no-ff --allow-unrelated-histories auto-merge/$GITHUB_HEAD_REF; then
            # Successful merge
            git push origin auto-merge/$GITHUB_HEAD_REF:QA
            echo "Merged QA."
          else
            output=$(git merge --no-ff $GITHUB_HEAD_REF)
            echo $output
            # Merge conflict
            echo "Merge conflict, aborting automatic merge."
            # Optionally, you can notify someone or take other actions here
          fi

          # Clean up branch
          git checkout QA
          git branch -D auto-merge/$GITHUB_HEAD_REF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
