name: Auto Merge on Label

on:
  pull_request:
    types: [labeled]
    
env:
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

jobs:
  main:
    if: ${{ github.event.label.name == 'merge-to-qa' }}
    permissions:
      contents: write
      issues: write
    name: Merge QA
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
          
      - name: Debug
        run: |
          echo "Permissions: ${{ github.event.pull_request.head.repo.permissions }}"
          echo "Owner: ${{ github.event.pull_request.head.repo.owner.login }}"
          echo "Repo: ${{ github.event.pull_request.head.repo.name }}"

      - name: perform merge
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git status
          git remote add upstream https://github.com/documentos-digitales-lab/pruebas-prs.git
          git fetch --all
          git checkout -b QA upstream/QA
          echo "checkout=> upstream/QA"
          git status
          echo "checkout FEAT=> $GITHUB_HEAD_REF"
          git merge "$GITHUB_HEAD_REF" --no-edit
          echo "merged $GITHUB_HEAD_REF into QA "
          git push https://${USERNAME}:${GITHUB_TOKEN}@github.com/documentos-digitales-lab/pruebas-prs upstream QA --verbose
          echo "Pushed"
          git status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.event.pull_request.head.repo.owner.login }}

      - name: remove label
        if: always()
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: merge-to-qa
